spring:
  application:
    name: config-server
  profiles:
    active: native
server:
  port: ${PORT:8001}
logging:
  pattern:
    console: "%d{yy-MM-dd E HH:mm:ss.SSS} %highlight(%-5p) ${PID} --- %clr([%8.15t]){cyan} %highlight(%logger{36}){blue} : %m %n"
  level:
    org.springframework.web: INFO